Supply mandatory metadata in writer example
openzim/python-libzim pull request #193
Opened 2024-06-30 16:05 UTC by stuartlangridge

A zim file has certain mandatory requirements in the metadata; for example, Language, Date, and Illustration must be present. If they aren't, then some ZIM reader apps (such as Kiwix for iOS) will refuse to open the zim file. So, add these mandatory pieces to the example code in the readme, so that if you generate a zim file by following the example code, it will be valid.
(Discovered in https://github.com/kiwix/kiwix-apple/issues/842)

2024-07-02 17:26 UTC, rgaudin requested changes
Thank you ; I'm not convinced it's required but it doesn't hurt.
Please see inline change requests

2024-07-02 17:26 UTC, rgaudin commented on README.md
> +    illustration = open("icon48x48.png", mode="rb").read()
```suggestion
    illustration = pathlib.Path("icon48x48.png").read_bytes()
```
This is safer and cleaner

2024-07-02 17:26 UTC, rgaudin commented on README.md
> +        "language": "en",
```suggestion
        "language": "eng",
```
should be ISO-639-3

2024-07-03 06:55 UTC, stuartlangridge commented
Sure thing; those changes seem fine to me!

2024-07-03 10:13 UTC, rgaudin approved these changes
Thank you!

2024-07-03 10:13 UTC, merged